# This file is automatically generated. Do not edit.

if Object.const_defined?('TestFlight') and !UIDevice.currentDevice.model.include?('Simulator')
  NSNotificationCenter.defaultCenter.addObserverForName(UIApplicationDidBecomeActiveNotification, object:nil, queue:nil, usingBlock:lambda do |notification|
  TestFlight.takeOff('a76d6d9c00b59b21be662cb7bec366a2_NzI5MjUyMDEyLTAzLTE5IDE0OjM4OjUxLjgyNTQwMg')
  end)
end
